### ISSUE TITLE
Persistent history

### ISSUE THREAD

**Issue by eush77** [toddself/repl-it#13]
[`repl.history`](http://npm.im/repl.history) is a great little module that can load a history file into repl and update it with new user input. I have this in my Node repl for a while and I would like having support for this across repl-it repls, too.

@toddself What are your thoughts on this? Is this feature worth adding? Should it be under flag?

**Comment by toddself** [comment]
@eush77 this would be an awesome feature to add.  I'd enable it by default but add in an optional flag to disable it?

**Comment by toddself** [comment]
Added in version 2.2.0. Only works in io.js v1.0 and higher due to changes to streams implementation.

**Comment by eush77** [comment]
Great!

**Comment by eush77** [comment]
@toddself What's the motivation behind not using Node's own history file?

**Comment by toddself** [comment]
There is no default, just a shell env variable to set  

I figure that you might not want to "pollute" your normal queue since this repl instance assumes that a bunch of code has already been required for you. 

I probably should make it so that you can specify your own file so if you want to use the same, so be it!

**Comment by toddself** [comment]
You can override the default history file by setting the environment variable that node uses.  So if you're exporting this out, it'll just pick it up now :).

Also, there's a man page!

**Comment by eush77** [comment]
Wow, didn't even know npm supports man pages! Cool :+1:
